;;; guix-dotfiles.el --- Jump to Git source of Guix Home dotfiles  -*- lexical-binding: t; -*-

(defgroup guix-dotfiles nil
  "Utilities for navigating Guix Home managed dotfiles."
  :group 'tools)

(defcustom guix-dotfiles-manifest-path "~/.dotfiles-manifest"
  "Path to the manifest file generated by the Guix dotfiles-manifest-service."
  :type 'file
  :group 'guix-dotfiles)

(defun guix-dotfiles--read-manifest ()
  "Read the manifest file and return the alist, or nil if missing."
  (if (file-exists-p guix-dotfiles-manifest-path)
      (with-temp-buffer
        (insert-file-contents guix-dotfiles-manifest-path)
        (read (current-buffer)))
    nil))

;;;###autoload
(defun guix-dotfiles-jump ()
  "Jump to the git-controlled source of the current file.
Throws an error if the manifest is missing or if the file is not tracked."
  (interactive)
  (unless (buffer-file-name)
    (user-error "Buffer is not visiting a file"))

  (let ((manifest (guix-dotfiles--read-manifest))
        (current-file (file-truename (buffer-file-name)))
        (home (expand-file-name "~")))

    (unless manifest
      (user-error "Guix dotfiles manifest not found at '%s'. Did you run 'guix home reconfigure'?"
                  guix-dotfiles-manifest-path))

    (catch 'found
      (dolist (entry manifest)
        (let* ((rel-target (car entry))
               (abs-source (cdr entry))
               (abs-target (expand-file-name rel-target home)))

          (when (string= (file-truename abs-target) current-file)
            (find-file abs-source)
            (message "Jumped to source: %s" abs-source)
            (throw 'found t))))

      (user-error "Current file is not tracked in the dotfiles manifest"))))

(provide 'guix-dotfiles)
